version: '3.4'
  
networks:
  web:
    external:
      name: web
services:
  cutting-ui:
    env_file:
      - .env
    labels:
      - 'traefik.backend=cutting-api'
      - 'traefik.port=4040'
      - 'traefik.frontend.rule=Host:api.valleycuttingsystems.net'
    networks:
      web:
    image: wayimp/cutting-api
    ports:
      - 4040:4040
      - 27019:27017